services:
  db:
    image: mysql:8.4
    container_name: macaron
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: dotachan
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  db-data:
